"""Spectroscopy controller — I/V, dI/dV, and time-spectroscopy operations.

Vertical manipulation (VERTMAN) is CreaTec's term for point spectroscopy:
the tip is held at a position, the bias is swept, and selected channels
(current, lock-in X/Y, etc.) are recorded as a function of bias.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from .stm_client import STMClient


@dataclass
class IVTable:
    """Voltage/Z table for vertical manipulation.

    The VERTMAN.IVTABLE format is a 6x8 matrix where rows correspond to
    segments and columns to (start, points, bias_start, bias_end, ...).
    For a simple symmetric bias sweep we use one segment.
    """
    bias_start_V: float = -0.7
    bias_end_V: float = 0.7
    points: int = 1024
    backward_sweep: bool = True

    def to_table(self) -> tuple[tuple[float, ...], ...]:
        """Build the 6x8 IV-table tuple expected by VERTMAN.IVTABLE."""
        row0 = (0.0, float(self.points), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
        row1 = (float(self.bias_start_V), float(self.bias_end_V),
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
        zero_row = (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
        return (row0, row1, zero_row, zero_row, zero_row, zero_row)


class SpectroscopyController:
    def __init__(self, client: "STMClient") -> None:
        self._c = client

    # ------------------------------------------------------------------
    # Configuration
    # ------------------------------------------------------------------

    def configure(
        self,
        table: IVTable,
        channels: tuple[str, ...] = ("Current(filtered)", "Lock-in X", "Lock-in Y"),
        duration_s: float = 10.0,
        repeat_count: int = 1,
        average_count: int = 1,
        lat_speed_nm_s: float = 1.0,
        preamp_exponent: int = 9,
    ) -> None:
        c = self._c
        c.setp("VERTMAN.PREAMPGAIN.EXPONENT", int(preamp_exponent))
        c.setp("VERTMAN.IVTABLE", table.to_table())
        c.setp("VERTMAN.SPEC.BACK", 1 if table.backward_sweep else 0)
        c.setp("VERTMAN.CHANNELs", tuple(channels))
        c.setp("VERTMAN.LATSPEED.NM/SEC", float(lat_speed_nm_s))
        c.setp("VERTMAN.REPEATCOUNT", int(repeat_count))
        c.setp("VERTMAN.SPECAVRG.COUNT", int(average_count))
        c.setp("VERTMAN.SPECLENGTH.SEC", float(duration_s))

    # ------------------------------------------------------------------
    # Single-point spectroscopy
    # ------------------------------------------------------------------

    def single_at_pixel(self, x: int, y: int) -> None:
        """Record a single spectrum at the given pixel position in the current scan frame."""
        self._c.setp("VERTMAN.CMD.SINGLE_SPECTRUM", (int(x), int(y)))

    def multi_at_pixels(self, positions: list[tuple[int, int]]) -> None:
        """Record spectra at a list of (x, y) pixel positions sequentially."""
        flat = tuple((int(p[0]), int(p[1])) for p in positions)
        self._c.raw.btn_vertspec_mult(flat)

    def line_between(self, x1: int, y1: int, x2: int, y2: int) -> None:
        """Record evenly-spaced spectra along a line between two pixel positions."""
        self._c.raw.btn_vertspec_line(int(x1), int(y1), int(x2), int(y2))

    def grid(self) -> None:
        """Run the configured spectra-on-grid measurement.

        Note: grid origin / spacing / N×M are configured in the native
        STMAFM GUI (VERTMAN grid dialog). This call just triggers execution
        with whatever the instrument has stored.
        """
        self._c.raw.btn_spectraongrid()

    def grid_at_pixels(self, positions: list[tuple[int, int]]) -> None:
        """Run spectra at an arbitrary list of pixel positions.

        This is a thin wrapper around the multi-point spec that handles
        the most common case: a regular grid of points generated by the
        caller. Use :meth:`build_grid_positions` to build the list.
        """
        self.multi_at_pixels(positions)

    @staticmethod
    def build_grid_positions(
        origin_xy: tuple[int, int],
        size_xy: tuple[int, int],
        spacing_xy: tuple[int, int],
    ) -> list[tuple[int, int]]:
        """Generate (x, y) pixel positions for a regular grid.

        Parameters
        ----------
        origin_xy:
            Top-left corner (x, y) in image pixels.
        size_xy:
            (n_cols, n_rows) — how many points in each direction.
        spacing_xy:
            (dx, dy) pixel distance between successive points.
        """
        x0, y0 = origin_xy
        nx, ny = size_xy
        dx, dy = spacing_xy
        return [
            (x0 + j * dx, y0 + i * dy)
            for i in range(ny)
            for j in range(nx)
        ]

    # ------------------------------------------------------------------
    # Time spectroscopy
    # ------------------------------------------------------------------

    def time_spec_start(self) -> None:
        self._c.raw.btn_timespec()

    # ------------------------------------------------------------------
    # Save
    # ------------------------------------------------------------------

    def save_vert(self, filepath: str) -> None:
        """Save the most recent vertical-manipulation spectrum to .VERT."""
        self._c.setp("STMAFM.FILE.SAVE.VERT", str(filepath))

    def last_saved_vert(self) -> Optional[str]:
        try:
            return str(self._c.raw.savevertfilename) or None
        except Exception:
            return None
